openapi: '3.1.2'
info:
  title: National Parks API
  description: A REST API that gives information about national parks
  version: '1.0'
servers:
  - url: http://localhost/parks-api
paths:
 /vegetations:
    get:
      description: 'Get the list of vegetation '
      parameters:
        - name: type
          in: query
          description: type of vegetation
          required: false
          schema:
            type: string
            enum:
              - tree
              - flower
              - shrub
              - grass
        - name: bloom
          in: query
          description: bloom season of vegetation
          required: false
          schema:
            type: string
            enum:
              - winter
              - spring
              - summer
              - fall
        - name: growth
          in: query
          description: growth rate of vegetation
          required: false
          schema:
            type: string
            enum:
              - fast
              - moderate
              - slow
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found

